# Generated by Django 4.2.4 on 2023-11-06 05:47

import core.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('initialLat', models.FloatField()),
                ('initialLng', models.FloatField()),
                ('selectedMaterial', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('area', models.FloatField()),
                ('address', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='SolarOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('value', models.FloatField()),
                ('description', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OptionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to=core.models.image_upload_path)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.solaroption')),
            ],
        ),
    ]
