# Generated by Django 4.2.4 on 2023-10-19 11:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('initialLat', models.FloatField()),
                ('initialLng', models.FloatField()),
                ('selectedMaterial', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('area', models.FloatField()),
            ],
        ),
    ]
