# Generated by Django 4.2.4 on 2023-10-19 11:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
